package com.ngoducduy.celestialarts.alchemy;

import com.ngoducduy.celestialarts.skill.Element;
import net.minecraft.text.Text;
import net.minecraft.util.Formatting;

/**
 * Linh dược – one herb species. Pure data: which element it belongs to, its grade (phẩm, 1–5),
 * where it grows, what it may root on, and the alchemical properties the furnace works with:
 * <ul>
 *   <li>{@link #nature()} – hàn/nhiệt, −3 (freezing) … +3 (scorching). The heat a pill wants
 *       depends on the natures of its herbs; a cold herb in a hot fire is the first thing that
 *       goes wrong;</li>
 *   <li>{@link #potency()} – dược lực 1–12, how much medicine the herb contributes;</li>
 *   <li>{@link #toxicity()} – 0–5, residue that has to be refined out or the pill is impure.</li>
 * </ul>
 * The table itself lives in {@link HerbList} (generated by {@code tools/gen_herbs.py}).
 */
public record Herb(String key, Element element, int grade, Habitat habitat, int nature, int potency, int toxicity, int rgb) {

	/** Where a species grows – decides the world-gen feature it is put in and its footing. */
	public enum Habitat {
		MEADOW(Ground.SOIL, Placement.SURFACE),
		FOREST(Ground.SOIL, Placement.SURFACE),
		JUNGLE(Ground.SOIL, Placement.SURFACE),
		SWAMP(Ground.SOIL, Placement.SURFACE),
		MOUNTAIN(Ground.SOIL_OR_STONE, Placement.SURFACE),
		SNOW(Ground.SOIL_OR_SNOW, Placement.SURFACE),
		DESERT(Ground.SAND_OR_SOIL, Placement.SURFACE),
		BEACH(Ground.SAND_OR_SOIL, Placement.SURFACE),
		CHERRY(Ground.SOIL, Placement.SURFACE),
		CAVE(Ground.STONE, Placement.CAVE),
		DEEP(Ground.STONE, Placement.DEEP),
		LUSH(Ground.SOIL_OR_STONE, Placement.CAVE),
		NETHER(Ground.NETHER, Placement.NETHER),
		END(Ground.END, Placement.SURFACE);

		private final Ground ground;
		private final Placement placement;

		Habitat(Ground ground, Placement placement) {
			this.ground = ground;
			this.placement = placement;
		}

		public Ground getGround() {
			return ground;
		}

		public Placement getPlacement() {
			return placement;
		}

		public String getKey() {
			return name().toLowerCase();
		}

		public Text getName() {
			return Text.translatable("habitat.celestialarts." + getKey());
		}
	}

	/** Block families a species can root on. */
	public enum Ground { SOIL, SOIL_OR_STONE, SOIL_OR_SNOW, SAND_OR_SOIL, STONE, NETHER, END }

	/** How the world-gen feature places the patch. */
	public enum Placement { SURFACE, CAVE, DEEP, NETHER }

	public String blockKey() {
		return "herb_" + key;
	}

	public Text getName() {
		return Text.translatable("block.celestialarts." + blockKey()).formatted(gradeFormatting(grade));
	}

	public Text getGradeName() {
		return Text.translatable("herb.celestialarts.grade." + grade).formatted(gradeFormatting(grade));
	}

	/** Hàn / Lương / Bình / Ôn / Nhiệt – the five natures of traditional medicine, from {@link #nature()}. */
	public Text getNatureName() {
		String k = nature <= -2 ? "cold" : nature == -1 ? "cool" : nature == 0 ? "neutral" : nature == 1 ? "warm" : "hot";
		Formatting f = nature <= -2 ? Formatting.AQUA : nature == -1 ? Formatting.BLUE : nature == 0 ? Formatting.WHITE : nature == 1 ? Formatting.YELLOW : Formatting.RED;
		return Text.translatable("herb.celestialarts.nature." + k).formatted(f);
	}

	public static Formatting gradeFormatting(int grade) {
		return switch (grade) {
			case 1 -> Formatting.WHITE;
			case 2 -> Formatting.GREEN;
			case 3 -> Formatting.AQUA;
			case 4 -> Formatting.LIGHT_PURPLE;
			default -> Formatting.GOLD;
		};
	}

	/** World-gen weight inside its habitat patch: common herbs crowd out the rare ones. */
	public int spawnWeight() {
		return switch (grade) {
			case 1 -> 12;
			case 2 -> 7;
			case 3 -> 3;
			case 4 -> 2;
			default -> 1;
		};
	}

	/** Grade 4–5 herbs go in the rare patch of their habitat, everything else in the common one. */
	public boolean isRare() {
		return grade >= 4;
	}
}
