package com.ngoducduy.celestialarts.worldgen;

import com.ngoducduy.celestialarts.CelestialArts;
import com.ngoducduy.celestialarts.alchemy.Herb;
import com.ngoducduy.celestialarts.alchemy.Herbs;
import net.fabricmc.fabric.api.biome.v1.BiomeModifications;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectionContext;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectors;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.tag.BiomeTags;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.biome.BiomeKeys;
import net.minecraft.world.gen.GenerationStep;
import net.minecraft.world.gen.feature.PlacedFeature;

import java.util.function.Predicate;

/**
 * Hooks the herb patches (data/celestialarts/worldgen, generated by tools/gen_herbs.py) into the
 * vanilla biomes of each habitat. Each habitat has a common patch (grade 1–3) and a rare one
 * (grade 4–5). A dedicated cultivation biome is planned for later; until then herbs grow where
 * their nature fits – fire herbs in deserts and the Nether, ice herbs on snowy peaks, and so on.
 */
public final class ModWorldGen {
	private ModWorldGen() {
	}

	public static void register() {
		for (Herb.Habitat habitat : Herb.Habitat.values()) {
			boolean hasCommon = Herbs.inHabitat(habitat).stream().anyMatch(h -> !h.isRare());
			boolean hasRare = Herbs.inHabitat(habitat).stream().anyMatch(Herb::isRare);
			Predicate<BiomeSelectionContext> selector = selector(habitat);
			if (hasCommon) add(selector, "herbs_" + habitat.getKey() + "_common");
			if (hasRare) add(selector, "herbs_" + habitat.getKey() + "_rare");
		}
	}

	private static void add(Predicate<BiomeSelectionContext> selector, String name) {
		RegistryKey<PlacedFeature> key = RegistryKey.of(RegistryKeys.PLACED_FEATURE, CelestialArts.id(name));
		BiomeModifications.addFeature(selector, GenerationStep.Feature.VEGETAL_DECORATION, key);
	}

	@SafeVarargs
	private static Predicate<BiomeSelectionContext> keys(RegistryKey<Biome>... keys) {
		return BiomeSelectors.includeByKey(keys);
	}

	public static Predicate<BiomeSelectionContext> selector(Herb.Habitat habitat) {
		return switch (habitat) {
			case MEADOW -> keys(BiomeKeys.PLAINS, BiomeKeys.SUNFLOWER_PLAINS, BiomeKeys.MEADOW, BiomeKeys.FLOWER_FOREST);
			case FOREST -> BiomeSelectors.tag(BiomeTags.IS_FOREST).or(BiomeSelectors.tag(BiomeTags.IS_TAIGA))
					.and(keys(BiomeKeys.FLOWER_FOREST, BiomeKeys.CHERRY_GROVE).negate());
			case JUNGLE -> BiomeSelectors.tag(BiomeTags.IS_JUNGLE);
			case SWAMP -> keys(BiomeKeys.SWAMP, BiomeKeys.MANGROVE_SWAMP);
			case MOUNTAIN -> BiomeSelectors.tag(BiomeTags.IS_MOUNTAIN).or(BiomeSelectors.tag(BiomeTags.IS_HILL))
					.or(keys(BiomeKeys.STONY_PEAKS, BiomeKeys.WINDSWEPT_GRAVELLY_HILLS, BiomeKeys.WINDSWEPT_HILLS, BiomeKeys.WINDSWEPT_FOREST));
			case SNOW -> keys(BiomeKeys.SNOWY_PLAINS, BiomeKeys.SNOWY_TAIGA, BiomeKeys.SNOWY_SLOPES, BiomeKeys.GROVE, BiomeKeys.ICE_SPIKES,
					BiomeKeys.FROZEN_PEAKS, BiomeKeys.JAGGED_PEAKS, BiomeKeys.SNOWY_BEACH, BiomeKeys.FROZEN_RIVER);
			case DESERT -> keys(BiomeKeys.DESERT, BiomeKeys.SAVANNA, BiomeKeys.SAVANNA_PLATEAU, BiomeKeys.WINDSWEPT_SAVANNA)
					.or(BiomeSelectors.tag(BiomeTags.IS_BADLANDS));
			case BEACH -> BiomeSelectors.tag(BiomeTags.IS_BEACH).or(keys(BiomeKeys.STONY_SHORE));
			case CHERRY -> keys(BiomeKeys.CHERRY_GROVE);
			case CAVE, DEEP -> BiomeSelectors.foundInOverworld();
			case LUSH -> keys(BiomeKeys.LUSH_CAVES);
			case NETHER -> BiomeSelectors.foundInTheNether();
			case END -> keys(BiomeKeys.END_HIGHLANDS, BiomeKeys.END_MIDLANDS, BiomeKeys.SMALL_END_ISLANDS, BiomeKeys.END_BARRENS);
		};
	}
}
